services:
  - type: web
    name: jurnalin
    runtime: go
    buildCommand: go build -o jurnalin main.go
    startCommand: ./jurnalin
    envVars:
      - key: GIN_MODE
        value: release
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        fromEnvVar: SUPABASE_URL
      - key: SUPABASE_KEY
        fromEnvVar: SUPABASE_KEY
    healthCheckPath: /
    autoDeploy: true
